const SUMA = require('./ModulosLocales/sumar');
const RESTA = require('./ModulosLocales/restar');
const MULTIPLICA = require('./ModulosLocales/multiplicar');
const DIVIDE = require('./ModulosLocales/dividir');
console.log(SUMA(5, 6));
console.log(RESTA(7, 8));
console.log(MULTIPLICA(5, 6));
console.log(MULTIPLICA(123, 0));
console.log(DIVIDE(10, 2));
console.log(DIVIDE(20, 0));